spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.11.8:3306/yxc_database
      username: xtkj
      password: xtkj123
      driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
