spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_books
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp